### ISSUE TITLE
Keep Lifecycle methods together

### ISSUE THREAD

**Issue by passsy** [grandcentrix/AndroidCodeStyle#3]
Our internal developer survey shows that our developers want to keep Android Lifecycle methods together (for `Activities` and `Fragments`), in the correct order and before all other methods. They should not be sorted alphabetically like all other methods. #6 

<img width="770" alt="survey" src="https://user-images.githubusercontent.com/1096485/30854088-f2c70040-a2b0-11e7-907d-1d18154a15f5.png">

### Why is this beneficial? 
- `Activities` and `Fragments` should not contain business logic instead those classes provide callbacks for the Android Framework. Those methods are called in special order. Having this order in code helps to know when things are ready to be called.
- When sorting those methods alphabetical and mix them with all others, they can end up in wrong order (although it actually works most of the time) or mix with other methods which are completely unrelated.
- `Activity` lifecycle methods are `protected` whereas `Fragment` ones are `public`. When grouping by visibility those from `Activity` end up after all `public` methods. Especially those should be moved right after the constructor.

**Comment by passsy** [comment]
Implemented: https://github.com/grandcentrix/AndroidCodeStyle/commit/c5a13f57eef506168a154e52d12ae7afafa0fda1

**Comment by StefMa** [comment]
🙃

On Sep 26, 2017 12:26 PM, "Pascal Welsch" <notifications@github.com> wrote:

Implemented: c5a13f5
<https://github.com/grandcentrix/AndroidCodeStyle/commit/c5a13f57eef506168a154e52d12ae7afafa0fda1>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/grandcentrix/AndroidCodeStyle/issues/3#issuecomment-332155672>,
or mute the thread

**Comment by StefMa** [comment]
🙃
